version: "3.8"
services:
  task:
    build: .
    ports:
      - 8501:8501
    volumes:
      #- C:\Users\son\KEWMANN\Fraud POC\poc-bank-dki\data:/data
      - /home/bankdki/data:/data 
    restart: always